language: python
python:
- '3.5'
install:
- pip install nose
- pip install -r requirements.txt
script: nosetests -s --verbosity=3
deploy:
  provider: pypi
  user: mainro
  password:
    secure: zReXh3xD92fnZ8lkdYBaMDVGsBCr5is8BBH385lEwvvF1YWynOYMtFqOJsLAkpCLpchKhaFR2tfXRGyFMDDOsEFcQ4cZpQldmKThBaI7xAkNDnb05tF1j82x3IH1FOMJt8Oq4AYtpqopJRzmnuEaPr1mJSKkUGt20LPHcSZru9vbIFe0WKDmr5loiOIH8nJ5y2mm6WCmdkns4/wCtaGmjnIWoyNbV8ia53FsXAcjegpN3CcZrX5zo18IZrg5eNS32gIK9JUB4fheSHRy0o/2Mw2cg/9AnTRTq6j1dKaR/X0bTRHpD/3tOUT88ToPoOsHmXfnnSJDk6NwXEODaKwOKAmmNg1KKa5lGFqOgugTeeFtbmtD1G/pletX6zCEpXMQ8UI5gHrDb9SdF+Ov22Q3j+iCO8wh8vsuxCXCp7CU/AzY5JFqfZqKyBWupZULHnQPQfdof9I41WgBTjshWIcW7XKOiH5PBdkwoX/0G6A88PO4cMlXUacVc7ViWxj+KmkX4ISatTISbz6+vuMLREnEjUSpR1u+y0x5JQ/BHwFmfEJ9w+mg22TPQMapUADD6XkB4+OSII+T9SjVOW/TXRtF3LeSjAqILU2yhvtX9hj76ru+uWcrfwj8tZuCMVkoqd/8kLHB4U0yoX1Jx/spgCMO4y5JwaXIFNa69mZM3a9R628=
  on:
    tags: true
